version: '3'
services:
  toposoid-sat-solver-web:
    image: toposoid-sat-solver-web:0.5-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sat-solver-web
      - PLAY_HTTP_PORT=9009
      - TOPOSOID_MAX_SAT_SOLVER=EvalMaxSAT_bin
      - TOPOSOID_CNF_FILE_PATH=/tmp
    ports:
      - 9009:9009

