version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-sat-solver-web:
    image: toposoid-sat-solver-web:0.3-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.2
      - PLAY_HTTP_PORT=9009
      - MAX_SAT_SOLVER=EvalMaxSAT_bin
      - CNF_FILE_PATH=/tmp/test.cnf
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9009:9009

