version: '3'
services:
  toposoid-sat-solver-web:
    image: toposoid/toposoid-sat-solver-web:0.6-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9009
      - TOPOSOID_MAX_SAT_SOLVER=EvalMaxSAT_bin
      - TOPOSOID_CNF_FILE_PATH=/tmp
    ports:
      - 9009:9009




